# -*- coding: UTF-8 -*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import quickpassinfoservice_pb2 as quickpassinfoservice__pb2


class QuickPassInfoServiceStub(object):
  """闪付基本信息
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.validateMobile = channel.unary_unary(
        '/QuickPassInfoService/validateMobile',
        request_serializer=quickpassinfoservice__pb2.ValidateMobileRequest.SerializeToString,
        response_deserializer=quickpassinfoservice__pb2.ValidateMobileResponse.FromString,
        )
    self.queryByMobile = channel.unary_unary(
        '/QuickPassInfoService/queryByMobile',
        request_serializer=quickpassinfoservice__pb2.QueryByMobileRequest.SerializeToString,
        response_deserializer=quickpassinfoservice__pb2.QueryByMobileResponse.FromString,
        )
    self.openQuickPass = channel.unary_unary(
        '/QuickPassInfoService/openQuickPass',
        request_serializer=quickpassinfoservice__pb2.OpenQuickPassRequest.SerializeToString,
        response_deserializer=quickpassinfoservice__pb2.OpenQuickPassResponse.FromString,
        )


class QuickPassInfoServiceServicer(object):
  """闪付基本信息
  """

  def validateMobile(self, request, context):
    """验证手机号是否开通闪付
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryByMobile(self, request, context):
    """根据手机号查询
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def openQuickPass(self, request, context):
    """开通闪付
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_QuickPassInfoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'validateMobile': grpc.unary_unary_rpc_method_handler(
          servicer.validateMobile,
          request_deserializer=quickpassinfoservice__pb2.ValidateMobileRequest.FromString,
          response_serializer=quickpassinfoservice__pb2.ValidateMobileResponse.SerializeToString,
      ),
      'queryByMobile': grpc.unary_unary_rpc_method_handler(
          servicer.queryByMobile,
          request_deserializer=quickpassinfoservice__pb2.QueryByMobileRequest.FromString,
          response_serializer=quickpassinfoservice__pb2.QueryByMobileResponse.SerializeToString,
      ),
      'openQuickPass': grpc.unary_unary_rpc_method_handler(
          servicer.openQuickPass,
          request_deserializer=quickpassinfoservice__pb2.OpenQuickPassRequest.FromString,
          response_serializer=quickpassinfoservice__pb2.OpenQuickPassResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'QuickPassInfoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
