# -*- coding: UTF-8 -*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import businessoperationservice_pb2 as businessoperationservice__pb2


class BusinessOperationServiceStub(object):
  """
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.queryConsumePageInfo = channel.unary_unary(
        '/BusinessOperationService/queryConsumePageInfo',
        request_serializer=businessoperationservice__pb2.QueryPageInfoRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.ConsumePageInfoResponse.FromString,
        )
    self.insertNoticeInfo = channel.unary_unary(
        '/BusinessOperationService/insertNoticeInfo',
        request_serializer=businessoperationservice__pb2.NoticeInfoRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.NoticeInfoResponse.FromString,
        )
    self.staticsEquityTrendByAction = channel.unary_unary(
        '/BusinessOperationService/staticsEquityTrendByAction',
        request_serializer=businessoperationservice__pb2.StaticsEquityTrendByActionRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.StaticsEquityTrendByActionResponse.FromString,
        )
    self.queryFirstPageInfo = channel.unary_unary(
        '/BusinessOperationService/queryFirstPageInfo',
        request_serializer=businessoperationservice__pb2.FirstPageInfoRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.FirstPageInfoResponse.FromString,
        )
    self.getAccountInfo = channel.unary_unary(
        '/BusinessOperationService/getAccountInfo',
        request_serializer=businessoperationservice__pb2.AccountInfoRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.AccountInfoResponse.FromString,
        )
    self.queryConsumeRankByGroup = channel.unary_unary(
        '/BusinessOperationService/queryConsumeRankByGroup',
        request_serializer=businessoperationservice__pb2.DateRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.QueryConsumeRankByGroupResponse.FromString,
        )
    self.queryRechargePageInfo = channel.unary_unary(
        '/BusinessOperationService/queryRechargePageInfo',
        request_serializer=businessoperationservice__pb2.QueryPageInfoRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.RechargePageInfoResponse.FromString,
        )
    self.queryCorrectPageInfo = channel.unary_unary(
        '/BusinessOperationService/queryCorrectPageInfo',
        request_serializer=businessoperationservice__pb2.QueryPageInfoRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.CorrectPageInfoResponse.FromString,
        )
    self.queryNoticePageInfo = channel.unary_unary(
        '/BusinessOperationService/queryNoticePageInfo',
        request_serializer=businessoperationservice__pb2.QueryNoticePageRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.QueryNoticePageResponse.FromString,
        )
    self.queryNoticeInfoEffective = channel.unary_unary(
        '/BusinessOperationService/queryNoticeInfoEffective',
        request_serializer=businessoperationservice__pb2.QueryNoticeRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.NoticeInfoResponse.FromString,
        )
    self.updateNoticeInfo = channel.unary_unary(
        '/BusinessOperationService/updateNoticeInfo',
        request_serializer=businessoperationservice__pb2.UpdateNoticeRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.NoticeInfoResponse.FromString,
        )
    self.queryNoticeInfoDetail = channel.unary_unary(
        '/BusinessOperationService/queryNoticeInfoDetail',
        request_serializer=businessoperationservice__pb2.QueryNoticeDetailRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.NoticeInfoResponse.FromString,
        )
    self.getGroupPageInfoList = channel.unary_unary(
        '/BusinessOperationService/getGroupPageInfoList',
        request_serializer=businessoperationservice__pb2.QueryGroupRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.QueryGroupInfoResponse.FromString,
        )
    self.queryFsmSettleUnit = channel.unary_unary(
        '/BusinessOperationService/queryFsmSettleUnit',
        request_serializer=businessoperationservice__pb2.QueryFsmSettleRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.QueryFsmSettleResponse.FromString,
        )
    self.immediate = channel.unary_unary(
        '/BusinessOperationService/immediate',
        request_serializer=businessoperationservice__pb2.UpdateNoticeRequest.SerializeToString,
        response_deserializer=businessoperationservice__pb2.NoticeInfoResponse.FromString,
        )


class BusinessOperationServiceServicer(object):
  """
  """

  def queryConsumePageInfo(self, request, context):
    """查询消费记录
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def insertNoticeInfo(self, request, context):
    """添加公告接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def staticsEquityTrendByAction(self, request, context):
    """统计各权益账户类型近30日数据趋势
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryFirstPageInfo(self, request, context):
    """数据首页
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAccountInfo(self, request, context):
    """查询账户信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryConsumeRankByGroup(self, request, context):
    """查询集团消费量top10
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryRechargePageInfo(self, request, context):
    """查询充值记录
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryCorrectPageInfo(self, request, context):
    """查询冲正记录
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryNoticePageInfo(self, request, context):
    """查询公告list接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryNoticeInfoEffective(self, request, context):
    """查询当前有效期公告接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateNoticeInfo(self, request, context):
    """更新公告接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryNoticeInfoDetail(self, request, context):
    """查询单个公告
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getGroupPageInfoList(self, request, context):
    """查询集团列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryFsmSettleUnit(self, request, context):
    """查询结算主体列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def immediate(self, request, context):
    """立即生效发布终止接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BusinessOperationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'queryConsumePageInfo': grpc.unary_unary_rpc_method_handler(
          servicer.queryConsumePageInfo,
          request_deserializer=businessoperationservice__pb2.QueryPageInfoRequest.FromString,
          response_serializer=businessoperationservice__pb2.ConsumePageInfoResponse.SerializeToString,
      ),
      'insertNoticeInfo': grpc.unary_unary_rpc_method_handler(
          servicer.insertNoticeInfo,
          request_deserializer=businessoperationservice__pb2.NoticeInfoRequest.FromString,
          response_serializer=businessoperationservice__pb2.NoticeInfoResponse.SerializeToString,
      ),
      'staticsEquityTrendByAction': grpc.unary_unary_rpc_method_handler(
          servicer.staticsEquityTrendByAction,
          request_deserializer=businessoperationservice__pb2.StaticsEquityTrendByActionRequest.FromString,
          response_serializer=businessoperationservice__pb2.StaticsEquityTrendByActionResponse.SerializeToString,
      ),
      'queryFirstPageInfo': grpc.unary_unary_rpc_method_handler(
          servicer.queryFirstPageInfo,
          request_deserializer=businessoperationservice__pb2.FirstPageInfoRequest.FromString,
          response_serializer=businessoperationservice__pb2.FirstPageInfoResponse.SerializeToString,
      ),
      'getAccountInfo': grpc.unary_unary_rpc_method_handler(
          servicer.getAccountInfo,
          request_deserializer=businessoperationservice__pb2.AccountInfoRequest.FromString,
          response_serializer=businessoperationservice__pb2.AccountInfoResponse.SerializeToString,
      ),
      'queryConsumeRankByGroup': grpc.unary_unary_rpc_method_handler(
          servicer.queryConsumeRankByGroup,
          request_deserializer=businessoperationservice__pb2.DateRequest.FromString,
          response_serializer=businessoperationservice__pb2.QueryConsumeRankByGroupResponse.SerializeToString,
      ),
      'queryRechargePageInfo': grpc.unary_unary_rpc_method_handler(
          servicer.queryRechargePageInfo,
          request_deserializer=businessoperationservice__pb2.QueryPageInfoRequest.FromString,
          response_serializer=businessoperationservice__pb2.RechargePageInfoResponse.SerializeToString,
      ),
      'queryCorrectPageInfo': grpc.unary_unary_rpc_method_handler(
          servicer.queryCorrectPageInfo,
          request_deserializer=businessoperationservice__pb2.QueryPageInfoRequest.FromString,
          response_serializer=businessoperationservice__pb2.CorrectPageInfoResponse.SerializeToString,
      ),
      'queryNoticePageInfo': grpc.unary_unary_rpc_method_handler(
          servicer.queryNoticePageInfo,
          request_deserializer=businessoperationservice__pb2.QueryNoticePageRequest.FromString,
          response_serializer=businessoperationservice__pb2.QueryNoticePageResponse.SerializeToString,
      ),
      'queryNoticeInfoEffective': grpc.unary_unary_rpc_method_handler(
          servicer.queryNoticeInfoEffective,
          request_deserializer=businessoperationservice__pb2.QueryNoticeRequest.FromString,
          response_serializer=businessoperationservice__pb2.NoticeInfoResponse.SerializeToString,
      ),
      'updateNoticeInfo': grpc.unary_unary_rpc_method_handler(
          servicer.updateNoticeInfo,
          request_deserializer=businessoperationservice__pb2.UpdateNoticeRequest.FromString,
          response_serializer=businessoperationservice__pb2.NoticeInfoResponse.SerializeToString,
      ),
      'queryNoticeInfoDetail': grpc.unary_unary_rpc_method_handler(
          servicer.queryNoticeInfoDetail,
          request_deserializer=businessoperationservice__pb2.QueryNoticeDetailRequest.FromString,
          response_serializer=businessoperationservice__pb2.NoticeInfoResponse.SerializeToString,
      ),
      'getGroupPageInfoList': grpc.unary_unary_rpc_method_handler(
          servicer.getGroupPageInfoList,
          request_deserializer=businessoperationservice__pb2.QueryGroupRequest.FromString,
          response_serializer=businessoperationservice__pb2.QueryGroupInfoResponse.SerializeToString,
      ),
      'queryFsmSettleUnit': grpc.unary_unary_rpc_method_handler(
          servicer.queryFsmSettleUnit,
          request_deserializer=businessoperationservice__pb2.QueryFsmSettleRequest.FromString,
          response_serializer=businessoperationservice__pb2.QueryFsmSettleResponse.SerializeToString,
      ),
      'immediate': grpc.unary_unary_rpc_method_handler(
          servicer.immediate,
          request_deserializer=businessoperationservice__pb2.UpdateNoticeRequest.FromString,
          response_serializer=businessoperationservice__pb2.NoticeInfoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'BusinessOperationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
