# -*- coding: UTF-8 -*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import equityservice_pb2 as equityservice__pb2


class EquityServiceStub(object):
  """
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.open = channel.unary_unary(
        '/EquityService/open',
        request_serializer=equityservice__pb2.AccountRequest.SerializeToString,
        response_deserializer=equityservice__pb2.AccountResponse.FromString,
        )
    self.consume = channel.unary_unary(
        '/EquityService/consume',
        request_serializer=equityservice__pb2.ConsumeRequest.SerializeToString,
        response_deserializer=equityservice__pb2.ConsumeResponse.FromString,
        )
    self.correct = channel.unary_unary(
        '/EquityService/correct',
        request_serializer=equityservice__pb2.CorrectRequest.SerializeToString,
        response_deserializer=equityservice__pb2.CorrectResponse.FromString,
        )
    self.refund = channel.unary_unary(
        '/EquityService/refund',
        request_serializer=equityservice__pb2.RefundRequest.SerializeToString,
        response_deserializer=equityservice__pb2.RefundResponse.FromString,
        )
    self.recharge = channel.unary_unary(
        '/EquityService/recharge',
        request_serializer=equityservice__pb2.RechargeRequest.SerializeToString,
        response_deserializer=equityservice__pb2.RechargeResponse.FromString,
        )
    self.callBackInvoice = channel.unary_unary(
        '/EquityService/callBackInvoice',
        request_serializer=equityservice__pb2.CallBackInvoiceRequest.SerializeToString,
        response_deserializer=equityservice__pb2.CallBackInvoiceResponse.FromString,
        )
    self.updateAccount = channel.unary_unary(
        '/EquityService/updateAccount',
        request_serializer=equityservice__pb2.UpdateAccountRequest.SerializeToString,
        response_deserializer=equityservice__pb2.UpdateAccountResponse.FromString,
        )
    self.updateAlarm = channel.unary_unary(
        '/EquityService/updateAlarm',
        request_serializer=equityservice__pb2.AlarmRequest.SerializeToString,
        response_deserializer=equityservice__pb2.AlarmResponse.FromString,
        )
    self.transferAccount = channel.unary_unary(
        '/EquityService/transferAccount',
        request_serializer=equityservice__pb2.TransferAccountRequest.SerializeToString,
        response_deserializer=equityservice__pb2.AccountResponse.FromString,
        )
    self.queryRechargeDetail = channel.unary_unary(
        '/EquityService/queryRechargeDetail',
        request_serializer=equityservice__pb2.RechargeQueryRequest.SerializeToString,
        response_deserializer=equityservice__pb2.RechargeResponse.FromString,
        )
    self.queryRechargePageInfo = channel.unary_unary(
        '/EquityService/queryRechargePageInfo',
        request_serializer=equityservice__pb2.RechargePageInfoRequest.SerializeToString,
        response_deserializer=equityservice__pb2.RechargePageInfoResponse.FromString,
        )
    self.queryConsumeDetail = channel.unary_unary(
        '/EquityService/queryConsumeDetail',
        request_serializer=equityservice__pb2.ConsumeQueryRequest.SerializeToString,
        response_deserializer=equityservice__pb2.ConsumeResponse.FromString,
        )
    self.queryConsumePageInfo = channel.unary_unary(
        '/EquityService/queryConsumePageInfo',
        request_serializer=equityservice__pb2.ConsumePageInfoRequest.SerializeToString,
        response_deserializer=equityservice__pb2.ConsumePageInfoResponse.FromString,
        )
    self.queryCorrectDetail = channel.unary_unary(
        '/EquityService/queryCorrectDetail',
        request_serializer=equityservice__pb2.CorrectQueryRequest.SerializeToString,
        response_deserializer=equityservice__pb2.CorrectResponse.FromString,
        )
    self.queryCorrectPageInfo = channel.unary_unary(
        '/EquityService/queryCorrectPageInfo',
        request_serializer=equityservice__pb2.CorrectPageInfoRequest.SerializeToString,
        response_deserializer=equityservice__pb2.CorrectPageInfoResponse.FromString,
        )
    self.queryAccountPageInfo = channel.unary_unary(
        '/EquityService/queryAccountPageInfo',
        request_serializer=equityservice__pb2.AccountPageInfoRequest.SerializeToString,
        response_deserializer=equityservice__pb2.AccountPageInfoResponse.FromString,
        )
    self.queryParamAccountPageInfo = channel.unary_unary(
        '/EquityService/queryParamAccountPageInfo',
        request_serializer=equityservice__pb2.AccountPageParamInfoRequest.SerializeToString,
        response_deserializer=equityservice__pb2.AccountPageInfoResponse.FromString,
        )
    self.queryAccountDetail = channel.unary_unary(
        '/EquityService/queryAccountDetail',
        request_serializer=equityservice__pb2.AccountQueryRequest.SerializeToString,
        response_deserializer=equityservice__pb2.AccountResponse.FromString,
        )
    self.queryAccountAndAlarmDetail = channel.unary_unary(
        '/EquityService/queryAccountAndAlarmDetail',
        request_serializer=equityservice__pb2.AccountAndAlarmQueryRequest.SerializeToString,
        response_deserializer=equityservice__pb2.AccountAndAlarmPageInfoResponse.FromString,
        )
    self.updateAccountOpen = channel.unary_unary(
        '/EquityService/updateAccountOpen',
        request_serializer=equityservice__pb2.UpdateAccountOpenRequest.SerializeToString,
        response_deserializer=equityservice__pb2.UpdateAccountOpenResponse.FromString,
        )


class EquityServiceServicer(object):
  """
  """

  def open(self, request, context):
    """开户
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def consume(self, request, context):
    """资产消费接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def correct(self, request, context):
    """资产消费冲正接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def refund(self, request, context):
    """资产充值退款接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def recharge(self, request, context):
    """资产充值接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def callBackInvoice(self, request, context):
    """开票返回接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateAccount(self, request, context):
    """修改权益账户
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateAlarm(self, request, context):
    """修改权益账户报警阀值
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def transferAccount(self, request, context):
    """权益账户转账
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryRechargeDetail(self, request, context):
    """查询充值明细
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryRechargePageInfo(self, request, context):
    """查询充值列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryConsumeDetail(self, request, context):
    """查询消费明细
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryConsumePageInfo(self, request, context):
    """查询消费列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryCorrectDetail(self, request, context):
    """查询消费冲正明细
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryCorrectPageInfo(self, request, context):
    """查询消费冲正列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryAccountPageInfo(self, request, context):
    """获取权益账户列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryParamAccountPageInfo(self, request, context):
    """获取权益账户列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryAccountDetail(self, request, context):
    """获取账户明细
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryAccountAndAlarmDetail(self, request, context):
    """批量获取账户和余额报警明细
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateAccountOpen(self, request, context):
    """修改权益账户状态
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EquityServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'open': grpc.unary_unary_rpc_method_handler(
          servicer.open,
          request_deserializer=equityservice__pb2.AccountRequest.FromString,
          response_serializer=equityservice__pb2.AccountResponse.SerializeToString,
      ),
      'consume': grpc.unary_unary_rpc_method_handler(
          servicer.consume,
          request_deserializer=equityservice__pb2.ConsumeRequest.FromString,
          response_serializer=equityservice__pb2.ConsumeResponse.SerializeToString,
      ),
      'correct': grpc.unary_unary_rpc_method_handler(
          servicer.correct,
          request_deserializer=equityservice__pb2.CorrectRequest.FromString,
          response_serializer=equityservice__pb2.CorrectResponse.SerializeToString,
      ),
      'refund': grpc.unary_unary_rpc_method_handler(
          servicer.refund,
          request_deserializer=equityservice__pb2.RefundRequest.FromString,
          response_serializer=equityservice__pb2.RefundResponse.SerializeToString,
      ),
      'recharge': grpc.unary_unary_rpc_method_handler(
          servicer.recharge,
          request_deserializer=equityservice__pb2.RechargeRequest.FromString,
          response_serializer=equityservice__pb2.RechargeResponse.SerializeToString,
      ),
      'callBackInvoice': grpc.unary_unary_rpc_method_handler(
          servicer.callBackInvoice,
          request_deserializer=equityservice__pb2.CallBackInvoiceRequest.FromString,
          response_serializer=equityservice__pb2.CallBackInvoiceResponse.SerializeToString,
      ),
      'updateAccount': grpc.unary_unary_rpc_method_handler(
          servicer.updateAccount,
          request_deserializer=equityservice__pb2.UpdateAccountRequest.FromString,
          response_serializer=equityservice__pb2.UpdateAccountResponse.SerializeToString,
      ),
      'updateAlarm': grpc.unary_unary_rpc_method_handler(
          servicer.updateAlarm,
          request_deserializer=equityservice__pb2.AlarmRequest.FromString,
          response_serializer=equityservice__pb2.AlarmResponse.SerializeToString,
      ),
      'transferAccount': grpc.unary_unary_rpc_method_handler(
          servicer.transferAccount,
          request_deserializer=equityservice__pb2.TransferAccountRequest.FromString,
          response_serializer=equityservice__pb2.AccountResponse.SerializeToString,
      ),
      'queryRechargeDetail': grpc.unary_unary_rpc_method_handler(
          servicer.queryRechargeDetail,
          request_deserializer=equityservice__pb2.RechargeQueryRequest.FromString,
          response_serializer=equityservice__pb2.RechargeResponse.SerializeToString,
      ),
      'queryRechargePageInfo': grpc.unary_unary_rpc_method_handler(
          servicer.queryRechargePageInfo,
          request_deserializer=equityservice__pb2.RechargePageInfoRequest.FromString,
          response_serializer=equityservice__pb2.RechargePageInfoResponse.SerializeToString,
      ),
      'queryConsumeDetail': grpc.unary_unary_rpc_method_handler(
          servicer.queryConsumeDetail,
          request_deserializer=equityservice__pb2.ConsumeQueryRequest.FromString,
          response_serializer=equityservice__pb2.ConsumeResponse.SerializeToString,
      ),
      'queryConsumePageInfo': grpc.unary_unary_rpc_method_handler(
          servicer.queryConsumePageInfo,
          request_deserializer=equityservice__pb2.ConsumePageInfoRequest.FromString,
          response_serializer=equityservice__pb2.ConsumePageInfoResponse.SerializeToString,
      ),
      'queryCorrectDetail': grpc.unary_unary_rpc_method_handler(
          servicer.queryCorrectDetail,
          request_deserializer=equityservice__pb2.CorrectQueryRequest.FromString,
          response_serializer=equityservice__pb2.CorrectResponse.SerializeToString,
      ),
      'queryCorrectPageInfo': grpc.unary_unary_rpc_method_handler(
          servicer.queryCorrectPageInfo,
          request_deserializer=equityservice__pb2.CorrectPageInfoRequest.FromString,
          response_serializer=equityservice__pb2.CorrectPageInfoResponse.SerializeToString,
      ),
      'queryAccountPageInfo': grpc.unary_unary_rpc_method_handler(
          servicer.queryAccountPageInfo,
          request_deserializer=equityservice__pb2.AccountPageInfoRequest.FromString,
          response_serializer=equityservice__pb2.AccountPageInfoResponse.SerializeToString,
      ),
      'queryParamAccountPageInfo': grpc.unary_unary_rpc_method_handler(
          servicer.queryParamAccountPageInfo,
          request_deserializer=equityservice__pb2.AccountPageParamInfoRequest.FromString,
          response_serializer=equityservice__pb2.AccountPageInfoResponse.SerializeToString,
      ),
      'queryAccountDetail': grpc.unary_unary_rpc_method_handler(
          servicer.queryAccountDetail,
          request_deserializer=equityservice__pb2.AccountQueryRequest.FromString,
          response_serializer=equityservice__pb2.AccountResponse.SerializeToString,
      ),
      'queryAccountAndAlarmDetail': grpc.unary_unary_rpc_method_handler(
          servicer.queryAccountAndAlarmDetail,
          request_deserializer=equityservice__pb2.AccountAndAlarmQueryRequest.FromString,
          response_serializer=equityservice__pb2.AccountAndAlarmPageInfoResponse.SerializeToString,
      ),
      'updateAccountOpen': grpc.unary_unary_rpc_method_handler(
          servicer.updateAccountOpen,
          request_deserializer=equityservice__pb2.UpdateAccountOpenRequest.FromString,
          response_serializer=equityservice__pb2.UpdateAccountOpenResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'EquityService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
