# -*- coding: UTF-8 -*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import smsdataservice_pb2 as smsdataservice__pb2


class SMSDataServiceStub(object):
  """短信数据汇总统计相关
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.querySMSData = channel.unary_unary(
        '/SMSDataService/querySMSData',
        request_serializer=smsdataservice__pb2.SMSDataQuery.SerializeToString,
        response_deserializer=smsdataservice__pb2.SMSDataRes.FromString,
        )
    self.queryMarketSMS = channel.unary_unary(
        '/SMSDataService/queryMarketSMS',
        request_serializer=smsdataservice__pb2.SMSBulkQuery.SerializeToString,
        response_deserializer=smsdataservice__pb2.BulkList.FromString,
        )
    self.querySMSDataSelf = channel.unary_unary(
        '/SMSDataService/querySMSDataSelf',
        request_serializer=smsdataservice__pb2.SMSDataSelfQuery.SerializeToString,
        response_deserializer=smsdataservice__pb2.SMSDataResSelf.FromString,
        )


class SMSDataServiceServicer(object):
  """短信数据汇总统计相关
  """

  def querySMSData(self, request, context):
    """获取短信发送汇总数据
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryMarketSMS(self, request, context):
    """营销短信查询接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def querySMSDataSelf(self, request, context):
    """获取短信发送汇总数据客服
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SMSDataServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'querySMSData': grpc.unary_unary_rpc_method_handler(
          servicer.querySMSData,
          request_deserializer=smsdataservice__pb2.SMSDataQuery.FromString,
          response_serializer=smsdataservice__pb2.SMSDataRes.SerializeToString,
      ),
      'queryMarketSMS': grpc.unary_unary_rpc_method_handler(
          servicer.queryMarketSMS,
          request_deserializer=smsdataservice__pb2.SMSBulkQuery.FromString,
          response_serializer=smsdataservice__pb2.BulkList.SerializeToString,
      ),
      'querySMSDataSelf': grpc.unary_unary_rpc_method_handler(
          servicer.querySMSDataSelf,
          request_deserializer=smsdataservice__pb2.SMSDataSelfQuery.FromString,
          response_serializer=smsdataservice__pb2.SMSDataResSelf.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SMSDataService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
