# -*- coding: UTF-8 -*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import queryservice_pb2 as queryservice__pb2


class QueryServiceStub(object):
  """权益账户查询服务
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.queryAccountDetail = channel.unary_unary(
        '/QueryService/queryAccountDetail',
        request_serializer=queryservice__pb2.AccountInfoRequest.SerializeToString,
        response_deserializer=queryservice__pb2.AccountInfoResponse.FromString,
        )
    self.queryAccountDetailForShop = channel.unary_unary(
        '/QueryService/queryAccountDetailForShop',
        request_serializer=queryservice__pb2.AccountInfoRequestForShop.SerializeToString,
        response_deserializer=queryservice__pb2.AccountInfoResponseForShop.FromString,
        )
    self.queryAccountDetailForMonitor = channel.unary_unary(
        '/QueryService/queryAccountDetailForMonitor',
        request_serializer=queryservice__pb2.AccountInfoRequestForMonitor.SerializeToString,
        response_deserializer=queryservice__pb2.AccountInfoResponseForMonitor.FromString,
        )
    self.queryBusinessList = channel.unary_unary(
        '/QueryService/queryBusinessList',
        request_serializer=queryservice__pb2.SubBusinessListReq.SerializeToString,
        response_deserializer=queryservice__pb2.SubBusinessListResp.FromString,
        )
    self.queryBillListForShop = channel.unary_unary(
        '/QueryService/queryBillListForShop',
        request_serializer=queryservice__pb2.BillListReq.SerializeToString,
        response_deserializer=queryservice__pb2.BillListResponse.FromString,
        )
    self.queryRechargeDetail = channel.unary_unary(
        '/QueryService/queryRechargeDetail',
        request_serializer=queryservice__pb2.RechargeDetailReq.SerializeToString,
        response_deserializer=queryservice__pb2.RechargeDetailResponse.FromString,
        )
    self.queryConsumeDetail = channel.unary_unary(
        '/QueryService/queryConsumeDetail',
        request_serializer=queryservice__pb2.ConsumeDetailReq.SerializeToString,
        response_deserializer=queryservice__pb2.ConsumeDetailResponse.FromString,
        )
    self.queryRefundDetail = channel.unary_unary(
        '/QueryService/queryRefundDetail',
        request_serializer=queryservice__pb2.ConsumeDetailReq.SerializeToString,
        response_deserializer=queryservice__pb2.ConsumeDetailResponse.FromString,
        )
    self.queryIncomeExpDetail = channel.unary_unary(
        '/QueryService/queryIncomeExpDetail',
        request_serializer=queryservice__pb2.IncomeExpDetailReq.SerializeToString,
        response_deserializer=queryservice__pb2.IncomeExpDetailResponse.FromString,
        )
    self.querySettleList = channel.unary_unary(
        '/QueryService/querySettleList',
        request_serializer=queryservice__pb2.SettleListReq.SerializeToString,
        response_deserializer=queryservice__pb2.SettleListResponse.FromString,
        )
    self.querySettleDetail = channel.unary_unary(
        '/QueryService/querySettleDetail',
        request_serializer=queryservice__pb2.SettleDetailReq.SerializeToString,
        response_deserializer=queryservice__pb2.SettleDetailResponse.FromString,
        )
    self.querySettleListByTranNo = channel.unary_unary(
        '/QueryService/querySettleListByTranNo',
        request_serializer=queryservice__pb2.SettleListReqByTranNo.SerializeToString,
        response_deserializer=queryservice__pb2.SettleListResponse.FromString,
        )
    self.queryBillListForMonitor = channel.unary_unary(
        '/QueryService/queryBillListForMonitor',
        request_serializer=queryservice__pb2.BillListReqForMonitor.SerializeToString,
        response_deserializer=queryservice__pb2.BillListResponseForMonitor.FromString,
        )
    self.queryRechargeDetailForMonitor = channel.unary_unary(
        '/QueryService/queryRechargeDetailForMonitor',
        request_serializer=queryservice__pb2.RechargeDetailReqForMonitor.SerializeToString,
        response_deserializer=queryservice__pb2.RechargeDetailResponseForMonitor.FromString,
        )
    self.queryConsumeDetailForMonitor = channel.unary_unary(
        '/QueryService/queryConsumeDetailForMonitor',
        request_serializer=queryservice__pb2.ConsumeDetailReqForMonitor.SerializeToString,
        response_deserializer=queryservice__pb2.ConsumeDetailResponseForMonitor.FromString,
        )
    self.queryRefundDetailForMonitor = channel.unary_unary(
        '/QueryService/queryRefundDetailForMonitor',
        request_serializer=queryservice__pb2.ConsumeDetailReqForMonitor.SerializeToString,
        response_deserializer=queryservice__pb2.ConsumeDetailResponseForMonitor.FromString,
        )
    self.querySettleListForMonitor = channel.unary_unary(
        '/QueryService/querySettleListForMonitor',
        request_serializer=queryservice__pb2.SettleListReqForMonitor.SerializeToString,
        response_deserializer=queryservice__pb2.SettleListResponseForMonitor.FromString,
        )
    self.querySettleDetailForMonitor = channel.unary_unary(
        '/QueryService/querySettleDetailForMonitor',
        request_serializer=queryservice__pb2.SettleDetailReqForMonitor.SerializeToString,
        response_deserializer=queryservice__pb2.SettleDetailResponseForMonitor.FromString,
        )
    self.queryArrearageAccount = channel.unary_unary(
        '/QueryService/queryArrearageAccount',
        request_serializer=queryservice__pb2.ArrearageAccountReq.SerializeToString,
        response_deserializer=queryservice__pb2.ArrearageAccountRes.FromString,
        )


class QueryServiceServicer(object):
  """权益账户查询服务
  """

  def queryAccountDetail(self, request, context):
    """查询账户详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryAccountDetailForShop(self, request, context):
    """商户中心查询账户信息列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryAccountDetailForMonitor(self, request, context):
    """monitor查询账户信息列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryBusinessList(self, request, context):
    """获取业务子类型列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryBillListForShop(self, request, context):
    """商户中心查询交易账单列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryRechargeDetail(self, request, context):
    """查看详情-充值
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryConsumeDetail(self, request, context):
    """查看详情-消费
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryRefundDetail(self, request, context):
    """查看详情-退款
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryIncomeExpDetail(self, request, context):
    """查询收支明细
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def querySettleList(self, request, context):
    """查询结算信息列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def querySettleDetail(self, request, context):
    """查询结算详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def querySettleListByTranNo(self, request, context):
    """查询结算信息列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryBillListForMonitor(self, request, context):
    """monitor查询流水列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryRechargeDetailForMonitor(self, request, context):
    """monitor查看充值详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryConsumeDetailForMonitor(self, request, context):
    """monitor查看消费详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryRefundDetailForMonitor(self, request, context):
    """monitor查看退款详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def querySettleListForMonitor(self, request, context):
    """monitor查看结算详情列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def querySettleDetailForMonitor(self, request, context):
    """monitor查询结算详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryArrearageAccount(self, request, context):
    """是否存在欠费账户-按集团按类型
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'queryAccountDetail': grpc.unary_unary_rpc_method_handler(
          servicer.queryAccountDetail,
          request_deserializer=queryservice__pb2.AccountInfoRequest.FromString,
          response_serializer=queryservice__pb2.AccountInfoResponse.SerializeToString,
      ),
      'queryAccountDetailForShop': grpc.unary_unary_rpc_method_handler(
          servicer.queryAccountDetailForShop,
          request_deserializer=queryservice__pb2.AccountInfoRequestForShop.FromString,
          response_serializer=queryservice__pb2.AccountInfoResponseForShop.SerializeToString,
      ),
      'queryAccountDetailForMonitor': grpc.unary_unary_rpc_method_handler(
          servicer.queryAccountDetailForMonitor,
          request_deserializer=queryservice__pb2.AccountInfoRequestForMonitor.FromString,
          response_serializer=queryservice__pb2.AccountInfoResponseForMonitor.SerializeToString,
      ),
      'queryBusinessList': grpc.unary_unary_rpc_method_handler(
          servicer.queryBusinessList,
          request_deserializer=queryservice__pb2.SubBusinessListReq.FromString,
          response_serializer=queryservice__pb2.SubBusinessListResp.SerializeToString,
      ),
      'queryBillListForShop': grpc.unary_unary_rpc_method_handler(
          servicer.queryBillListForShop,
          request_deserializer=queryservice__pb2.BillListReq.FromString,
          response_serializer=queryservice__pb2.BillListResponse.SerializeToString,
      ),
      'queryRechargeDetail': grpc.unary_unary_rpc_method_handler(
          servicer.queryRechargeDetail,
          request_deserializer=queryservice__pb2.RechargeDetailReq.FromString,
          response_serializer=queryservice__pb2.RechargeDetailResponse.SerializeToString,
      ),
      'queryConsumeDetail': grpc.unary_unary_rpc_method_handler(
          servicer.queryConsumeDetail,
          request_deserializer=queryservice__pb2.ConsumeDetailReq.FromString,
          response_serializer=queryservice__pb2.ConsumeDetailResponse.SerializeToString,
      ),
      'queryRefundDetail': grpc.unary_unary_rpc_method_handler(
          servicer.queryRefundDetail,
          request_deserializer=queryservice__pb2.ConsumeDetailReq.FromString,
          response_serializer=queryservice__pb2.ConsumeDetailResponse.SerializeToString,
      ),
      'queryIncomeExpDetail': grpc.unary_unary_rpc_method_handler(
          servicer.queryIncomeExpDetail,
          request_deserializer=queryservice__pb2.IncomeExpDetailReq.FromString,
          response_serializer=queryservice__pb2.IncomeExpDetailResponse.SerializeToString,
      ),
      'querySettleList': grpc.unary_unary_rpc_method_handler(
          servicer.querySettleList,
          request_deserializer=queryservice__pb2.SettleListReq.FromString,
          response_serializer=queryservice__pb2.SettleListResponse.SerializeToString,
      ),
      'querySettleDetail': grpc.unary_unary_rpc_method_handler(
          servicer.querySettleDetail,
          request_deserializer=queryservice__pb2.SettleDetailReq.FromString,
          response_serializer=queryservice__pb2.SettleDetailResponse.SerializeToString,
      ),
      'querySettleListByTranNo': grpc.unary_unary_rpc_method_handler(
          servicer.querySettleListByTranNo,
          request_deserializer=queryservice__pb2.SettleListReqByTranNo.FromString,
          response_serializer=queryservice__pb2.SettleListResponse.SerializeToString,
      ),
      'queryBillListForMonitor': grpc.unary_unary_rpc_method_handler(
          servicer.queryBillListForMonitor,
          request_deserializer=queryservice__pb2.BillListReqForMonitor.FromString,
          response_serializer=queryservice__pb2.BillListResponseForMonitor.SerializeToString,
      ),
      'queryRechargeDetailForMonitor': grpc.unary_unary_rpc_method_handler(
          servicer.queryRechargeDetailForMonitor,
          request_deserializer=queryservice__pb2.RechargeDetailReqForMonitor.FromString,
          response_serializer=queryservice__pb2.RechargeDetailResponseForMonitor.SerializeToString,
      ),
      'queryConsumeDetailForMonitor': grpc.unary_unary_rpc_method_handler(
          servicer.queryConsumeDetailForMonitor,
          request_deserializer=queryservice__pb2.ConsumeDetailReqForMonitor.FromString,
          response_serializer=queryservice__pb2.ConsumeDetailResponseForMonitor.SerializeToString,
      ),
      'queryRefundDetailForMonitor': grpc.unary_unary_rpc_method_handler(
          servicer.queryRefundDetailForMonitor,
          request_deserializer=queryservice__pb2.ConsumeDetailReqForMonitor.FromString,
          response_serializer=queryservice__pb2.ConsumeDetailResponseForMonitor.SerializeToString,
      ),
      'querySettleListForMonitor': grpc.unary_unary_rpc_method_handler(
          servicer.querySettleListForMonitor,
          request_deserializer=queryservice__pb2.SettleListReqForMonitor.FromString,
          response_serializer=queryservice__pb2.SettleListResponseForMonitor.SerializeToString,
      ),
      'querySettleDetailForMonitor': grpc.unary_unary_rpc_method_handler(
          servicer.querySettleDetailForMonitor,
          request_deserializer=queryservice__pb2.SettleDetailReqForMonitor.FromString,
          response_serializer=queryservice__pb2.SettleDetailResponseForMonitor.SerializeToString,
      ),
      'queryArrearageAccount': grpc.unary_unary_rpc_method_handler(
          servicer.queryArrearageAccount,
          request_deserializer=queryservice__pb2.ArrearageAccountReq.FromString,
          response_serializer=queryservice__pb2.ArrearageAccountRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'QueryService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
