# -*- coding: UTF-8 -*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import semsmsqueueservice_pb2 as semsmsqueueservice__pb2


class SemSMSQueueServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendMessage = channel.unary_unary(
        '/SemSMSQueueService/sendMessage',
        request_serializer=semsmsqueueservice__pb2.SmsQueueReq.SerializeToString,
        response_deserializer=semsmsqueueservice__pb2.ResInfo.FromString,
        )
    self.queryQueueAndHis = channel.unary_unary(
        '/SemSMSQueueService/queryQueueAndHis',
        request_serializer=semsmsqueueservice__pb2.QuerySmsQueueAndHisReq.SerializeToString,
        response_deserializer=semsmsqueueservice__pb2.QuerySmsQueueAndHisRes.FromString,
        )


class SemSMSQueueServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryQueueAndHis(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SemSMSQueueServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.sendMessage,
          request_deserializer=semsmsqueueservice__pb2.SmsQueueReq.FromString,
          response_serializer=semsmsqueueservice__pb2.ResInfo.SerializeToString,
      ),
      'queryQueueAndHis': grpc.unary_unary_rpc_method_handler(
          servicer.queryQueueAndHis,
          request_deserializer=semsmsqueueservice__pb2.QuerySmsQueueAndHisReq.FromString,
          response_serializer=semsmsqueueservice__pb2.QuerySmsQueueAndHisRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SemSMSQueueService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
