# -*- coding: UTF-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: advertservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commons_pb2 as commons__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='advertservice.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\033com.hualala.app.advert.grpcB\nAdvertData'),
  serialized_pb=_b('\n\x13\x61\x64vertservice.proto\x1a\rcommons.proto\"g\n\x0e\x41\x64RouteRequest\x12\x14\n\x0c\x61\x64PositionId\x18\x02 \x01(\t\x12\x0f\n\x07groupId\x18\x08 \x01(\t\x12\x0e\n\x06shopId\x18\t \x01(\t\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.RequestHeader\"\xa9\x01\n\x0f\x41\x64RouteResponse\x12\x14\n\x0c\x61\x64PositionId\x18\x02 \x01(\t\x12\x12\n\nadMatterId\x18\x03 \x01(\t\x12\x12\n\nadvertType\x18\x04 \x01(\t\x12\x14\n\x0c\x66rontPageUri\x18\x05 \x01(\t\x12\x13\n\x0blandPageUri\x18\x06 \x01(\t\x12\x0e\n\x06isShow\x18\x07 \x01(\t\x12\x1d\n\x06result\x18\x01 \x01(\x0b\x32\r.ResultHeader2B\n\rAdvertService\x12\x31\n\ngetAdRoute\x12\x0f.AdRouteRequest\x1a\x10.AdRouteResponse\"\x00\x42)\n\x1b\x63om.hualala.app.advert.grpcB\nAdvertDatab\x06proto3')
  ,
  dependencies=[commons__pb2.DESCRIPTOR,])




_ADROUTEREQUEST = _descriptor.Descriptor(
  name='AdRouteRequest',
  full_name='AdRouteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adPositionId', full_name='AdRouteRequest.adPositionId', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groupId', full_name='AdRouteRequest.groupId', index=1,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shopId', full_name='AdRouteRequest.shopId', index=2,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header', full_name='AdRouteRequest.header', index=3,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=141,
)


_ADROUTERESPONSE = _descriptor.Descriptor(
  name='AdRouteResponse',
  full_name='AdRouteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adPositionId', full_name='AdRouteResponse.adPositionId', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='adMatterId', full_name='AdRouteResponse.adMatterId', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='advertType', full_name='AdRouteResponse.advertType', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frontPageUri', full_name='AdRouteResponse.frontPageUri', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landPageUri', full_name='AdRouteResponse.landPageUri', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isShow', full_name='AdRouteResponse.isShow', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='AdRouteResponse.result', index=6,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=313,
)

_ADROUTEREQUEST.fields_by_name['header'].message_type = commons__pb2._REQUESTHEADER
_ADROUTERESPONSE.fields_by_name['result'].message_type = commons__pb2._RESULTHEADER
DESCRIPTOR.message_types_by_name['AdRouteRequest'] = _ADROUTEREQUEST
DESCRIPTOR.message_types_by_name['AdRouteResponse'] = _ADROUTERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AdRouteRequest = _reflection.GeneratedProtocolMessageType('AdRouteRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADROUTEREQUEST,
  __module__ = 'advertservice_pb2'
  # @@protoc_insertion_point(class_scope:AdRouteRequest)
  ))
_sym_db.RegisterMessage(AdRouteRequest)

AdRouteResponse = _reflection.GeneratedProtocolMessageType('AdRouteResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADROUTERESPONSE,
  __module__ = 'advertservice_pb2'
  # @@protoc_insertion_point(class_scope:AdRouteResponse)
  ))
_sym_db.RegisterMessage(AdRouteResponse)


DESCRIPTOR._options = None

_ADVERTSERVICE = _descriptor.ServiceDescriptor(
  name='AdvertService',
  full_name='AdvertService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=315,
  serialized_end=381,
  methods=[
  _descriptor.MethodDescriptor(
    name='getAdRoute',
    full_name='AdvertService.getAdRoute',
    index=0,
    containing_service=None,
    input_type=_ADROUTEREQUEST,
    output_type=_ADROUTERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADVERTSERVICE)

DESCRIPTOR.services_by_name['AdvertService'] = _ADVERTSERVICE

# @@protoc_insertion_point(module_scope)
