# -*- coding: UTF-8 -*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import messageusersignservice_pb2 as messageusersignservice__pb2


class MessageUserSignServiceStub(object):
  """短信自有签名服务
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.qryMessageUserSign = channel.unary_unary(
        '/MessageUserSignService/qryMessageUserSign',
        request_serializer=messageusersignservice__pb2.QryMessageUserSignReq.SerializeToString,
        response_deserializer=messageusersignservice__pb2.QryMessageUserSignRes.FromString,
        )
    self.qryMsgUserSignList = channel.unary_unary(
        '/MessageUserSignService/qryMsgUserSignList',
        request_serializer=messageusersignservice__pb2.QryMsgUserSignReq.SerializeToString,
        response_deserializer=messageusersignservice__pb2.QryMsgUserSignListRes.FromString,
        )


class MessageUserSignServiceServicer(object):
  """短信自有签名服务
  """

  def qryMessageUserSign(self, request, context):
    """查询短信自有签名
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def qryMsgUserSignList(self, request, context):
    """查询短信签名列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessageUserSignServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'qryMessageUserSign': grpc.unary_unary_rpc_method_handler(
          servicer.qryMessageUserSign,
          request_deserializer=messageusersignservice__pb2.QryMessageUserSignReq.FromString,
          response_serializer=messageusersignservice__pb2.QryMessageUserSignRes.SerializeToString,
      ),
      'qryMsgUserSignList': grpc.unary_unary_rpc_method_handler(
          servicer.qryMsgUserSignList,
          request_deserializer=messageusersignservice__pb2.QryMsgUserSignReq.FromString,
          response_serializer=messageusersignservice__pb2.QryMsgUserSignListRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MessageUserSignService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
