# -*- coding: UTF-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messageusersignservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commons_pb2 as commons__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messageusersignservice.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n$com.hualala.app.message.channel.grpcB\023MessageUserSignData'),
  serialized_pb=_b('\n\x1cmessageusersignservice.proto\x1a\rcommons.proto\"\xd9\x01\n\x15QryMessageUserSignReq\x12\x0f\n\x07groupID\x18\x02 \x01(\x03\x12\x0f\n\x07\x62randID\x18\x03 \x01(\x03\x12\x0e\n\x06shopID\x18\x04 \x01(\x03\x12\x12\n\ncardTypeID\x18\x05 \x01(\x03\x12\x0f\n\x07sysCode\x18\x06 \x01(\t\x12\x13\n\x0bmessageType\x18\x07 \x01(\x05\x12\x10\n\x08sendType\x18\x08 \x01(\x05\x12\x12\n\nintTelCode\x18\t \x01(\t\x12\x0e\n\x06signID\x18\n \x01(\t\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.RequestHeader\"n\n\x15QryMessageUserSignRes\x12\x10\n\x08signName\x18\x02 \x01(\t\x12\x15\n\rchannelSignID\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\t\x12\x1d\n\x06result\x18\x01 \x01(\x0b\x32\r.ResultHeader\"\x81\x01\n\x11QryMsgUserSignReq\x12\x0f\n\x07groupID\x18\x03 \x01(\t\x12\x13\n\x0bmessageType\x18\x07 \x01(\x05\x12&\n\npageHeader\x18\x02 \x01(\x0b\x32\x12.RequestPageHeader\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.RequestHeader\"\x8f\x01\n\x15QryMsgUserSignListRes\x12\x1f\n\x07records\x18\x03 \x03(\x0b\x32\x0e.UserSignModel\x12\x0f\n\x07groupID\x18\x04 \x01(\t\x12%\n\npageHeader\x18\x02 \x01(\x0b\x32\x11.ResultPageHeader\x12\x1d\n\x06result\x18\x01 \x01(\x0b\x32\r.ResultHeader\"1\n\rUserSignModel\x12\x0e\n\x06signID\x18\x02 \x01(\t\x12\x10\n\x08signName\x18\x03 \x01(\t2\xa4\x01\n\x16MessageUserSignService\x12\x46\n\x12qryMessageUserSign\x12\x16.QryMessageUserSignReq\x1a\x16.QryMessageUserSignRes\"\x00\x12\x42\n\x12qryMsgUserSignList\x12\x12.QryMsgUserSignReq\x1a\x16.QryMsgUserSignListRes\"\x00\x42;\n$com.hualala.app.message.channel.grpcB\x13MessageUserSignDatab\x06proto3')
  ,
  dependencies=[commons__pb2.DESCRIPTOR,])




_QRYMESSAGEUSERSIGNREQ = _descriptor.Descriptor(
  name='QryMessageUserSignReq',
  full_name='QryMessageUserSignReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groupID', full_name='QryMessageUserSignReq.groupID', index=0,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brandID', full_name='QryMessageUserSignReq.brandID', index=1,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shopID', full_name='QryMessageUserSignReq.shopID', index=2,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cardTypeID', full_name='QryMessageUserSignReq.cardTypeID', index=3,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sysCode', full_name='QryMessageUserSignReq.sysCode', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageType', full_name='QryMessageUserSignReq.messageType', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sendType', full_name='QryMessageUserSignReq.sendType', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intTelCode', full_name='QryMessageUserSignReq.intTelCode', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signID', full_name='QryMessageUserSignReq.signID', index=8,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header', full_name='QryMessageUserSignReq.header', index=9,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=265,
)


_QRYMESSAGEUSERSIGNRES = _descriptor.Descriptor(
  name='QryMessageUserSignRes',
  full_name='QryMessageUserSignRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signName', full_name='QryMessageUserSignRes.signName', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channelSignID', full_name='QryMessageUserSignRes.channelSignID', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='QryMessageUserSignRes.price', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='QryMessageUserSignRes.result', index=3,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=377,
)


_QRYMSGUSERSIGNREQ = _descriptor.Descriptor(
  name='QryMsgUserSignReq',
  full_name='QryMsgUserSignReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groupID', full_name='QryMsgUserSignReq.groupID', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageType', full_name='QryMsgUserSignReq.messageType', index=1,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageHeader', full_name='QryMsgUserSignReq.pageHeader', index=2,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header', full_name='QryMsgUserSignReq.header', index=3,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=509,
)


_QRYMSGUSERSIGNLISTRES = _descriptor.Descriptor(
  name='QryMsgUserSignListRes',
  full_name='QryMsgUserSignListRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='QryMsgUserSignListRes.records', index=0,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groupID', full_name='QryMsgUserSignListRes.groupID', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageHeader', full_name='QryMsgUserSignListRes.pageHeader', index=2,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='QryMsgUserSignListRes.result', index=3,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=655,
)


_USERSIGNMODEL = _descriptor.Descriptor(
  name='UserSignModel',
  full_name='UserSignModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signID', full_name='UserSignModel.signID', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signName', full_name='UserSignModel.signName', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=657,
  serialized_end=706,
)

_QRYMESSAGEUSERSIGNREQ.fields_by_name['header'].message_type = commons__pb2._REQUESTHEADER
_QRYMESSAGEUSERSIGNRES.fields_by_name['result'].message_type = commons__pb2._RESULTHEADER
_QRYMSGUSERSIGNREQ.fields_by_name['pageHeader'].message_type = commons__pb2._REQUESTPAGEHEADER
_QRYMSGUSERSIGNREQ.fields_by_name['header'].message_type = commons__pb2._REQUESTHEADER
_QRYMSGUSERSIGNLISTRES.fields_by_name['records'].message_type = _USERSIGNMODEL
_QRYMSGUSERSIGNLISTRES.fields_by_name['pageHeader'].message_type = commons__pb2._RESULTPAGEHEADER
_QRYMSGUSERSIGNLISTRES.fields_by_name['result'].message_type = commons__pb2._RESULTHEADER
DESCRIPTOR.message_types_by_name['QryMessageUserSignReq'] = _QRYMESSAGEUSERSIGNREQ
DESCRIPTOR.message_types_by_name['QryMessageUserSignRes'] = _QRYMESSAGEUSERSIGNRES
DESCRIPTOR.message_types_by_name['QryMsgUserSignReq'] = _QRYMSGUSERSIGNREQ
DESCRIPTOR.message_types_by_name['QryMsgUserSignListRes'] = _QRYMSGUSERSIGNLISTRES
DESCRIPTOR.message_types_by_name['UserSignModel'] = _USERSIGNMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QryMessageUserSignReq = _reflection.GeneratedProtocolMessageType('QryMessageUserSignReq', (_message.Message,), dict(
  DESCRIPTOR = _QRYMESSAGEUSERSIGNREQ,
  __module__ = 'messageusersignservice_pb2'
  # @@protoc_insertion_point(class_scope:QryMessageUserSignReq)
  ))
_sym_db.RegisterMessage(QryMessageUserSignReq)

QryMessageUserSignRes = _reflection.GeneratedProtocolMessageType('QryMessageUserSignRes', (_message.Message,), dict(
  DESCRIPTOR = _QRYMESSAGEUSERSIGNRES,
  __module__ = 'messageusersignservice_pb2'
  # @@protoc_insertion_point(class_scope:QryMessageUserSignRes)
  ))
_sym_db.RegisterMessage(QryMessageUserSignRes)

QryMsgUserSignReq = _reflection.GeneratedProtocolMessageType('QryMsgUserSignReq', (_message.Message,), dict(
  DESCRIPTOR = _QRYMSGUSERSIGNREQ,
  __module__ = 'messageusersignservice_pb2'
  # @@protoc_insertion_point(class_scope:QryMsgUserSignReq)
  ))
_sym_db.RegisterMessage(QryMsgUserSignReq)

QryMsgUserSignListRes = _reflection.GeneratedProtocolMessageType('QryMsgUserSignListRes', (_message.Message,), dict(
  DESCRIPTOR = _QRYMSGUSERSIGNLISTRES,
  __module__ = 'messageusersignservice_pb2'
  # @@protoc_insertion_point(class_scope:QryMsgUserSignListRes)
  ))
_sym_db.RegisterMessage(QryMsgUserSignListRes)

UserSignModel = _reflection.GeneratedProtocolMessageType('UserSignModel', (_message.Message,), dict(
  DESCRIPTOR = _USERSIGNMODEL,
  __module__ = 'messageusersignservice_pb2'
  # @@protoc_insertion_point(class_scope:UserSignModel)
  ))
_sym_db.RegisterMessage(UserSignModel)


DESCRIPTOR._options = None

_MESSAGEUSERSIGNSERVICE = _descriptor.ServiceDescriptor(
  name='MessageUserSignService',
  full_name='MessageUserSignService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=709,
  serialized_end=873,
  methods=[
  _descriptor.MethodDescriptor(
    name='qryMessageUserSign',
    full_name='MessageUserSignService.qryMessageUserSign',
    index=0,
    containing_service=None,
    input_type=_QRYMESSAGEUSERSIGNREQ,
    output_type=_QRYMESSAGEUSERSIGNRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='qryMsgUserSignList',
    full_name='MessageUserSignService.qryMsgUserSignList',
    index=1,
    containing_service=None,
    input_type=_QRYMSGUSERSIGNREQ,
    output_type=_QRYMSGUSERSIGNLISTRES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGEUSERSIGNSERVICE)

DESCRIPTOR.services_by_name['MessageUserSignService'] = _MESSAGEUSERSIGNSERVICE

# @@protoc_insertion_point(module_scope)
