# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invoicecommons.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='invoicecommons.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x14invoicecommons.proto*H\n\x08UserType\x12\x07\n\x03HLL\x10\x00\x12\x08\n\x04USER\x10\x01\x12\x08\n\x04SHOP\x10\x02\x12\t\n\x05GROUP\x10\x03\x12\t\n\x05STOCK\x10\x04\x12\t\n\x05\x41GENT\x10\x05*N\n\rTransTypeEnum\x12\x0e\n\nSH_TO_USER\x10\x00\x12\r\n\tHLL_TO_SH\x10\x01\x12\r\n\tGYS_TO_SH\x10\x02\x12\x0f\n\x0bINVOICE_TRY\x10\x03*J\n\x06Status\x12\x08\n\x04WAIT\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x12\x07\n\x03ING\x10\x03\x12\x08\n\x04PART\x10\x04\x12\t\n\x05NOUSE\x10\x05*^\n\x0eInvoiceTagEnum\x12\x06\n\x02HT\x10\x00\x12\x06\n\x02\x42W\x10\x01\x12\x06\n\x02\x42S\x10\x02\x12\x06\n\x02IC\x10\x03\x12\x06\n\x02PT\x10\x04\x12\x08\n\x04HXGD\x10\x05\x12\n\n\x06YONYOU\x10\x06\x12\x0e\n\nYONYOU_ISV\x10\x07\x42-\n\x1c\x63om.hualala.app.invoice.grpcB\rInvoiceCommonb\x06proto3')
)

_USERTYPE = _descriptor.EnumDescriptor(
  name='UserType',
  full_name='UserType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HLL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHOP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GROUP', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOCK', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGENT', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=24,
  serialized_end=96,
)
_sym_db.RegisterEnumDescriptor(_USERTYPE)

UserType = enum_type_wrapper.EnumTypeWrapper(_USERTYPE)
_TRANSTYPEENUM = _descriptor.EnumDescriptor(
  name='TransTypeEnum',
  full_name='TransTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SH_TO_USER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HLL_TO_SH', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GYS_TO_SH', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVOICE_TRY', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=98,
  serialized_end=176,
)
_sym_db.RegisterEnumDescriptor(_TRANSTYPEENUM)

TransTypeEnum = enum_type_wrapper.EnumTypeWrapper(_TRANSTYPEENUM)
_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WAIT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ING', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PART', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOUSE', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=178,
  serialized_end=252,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
_INVOICETAGENUM = _descriptor.EnumDescriptor(
  name='InvoiceTagEnum',
  full_name='InvoiceTagEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IC', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HXGD', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YONYOU', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YONYOU_ISV', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=254,
  serialized_end=348,
)
_sym_db.RegisterEnumDescriptor(_INVOICETAGENUM)

InvoiceTagEnum = enum_type_wrapper.EnumTypeWrapper(_INVOICETAGENUM)
HLL = 0
USER = 1
SHOP = 2
GROUP = 3
STOCK = 4
AGENT = 5
SH_TO_USER = 0
HLL_TO_SH = 1
GYS_TO_SH = 2
INVOICE_TRY = 3
WAIT = 0
SUCCESS = 1
FAILURE = 2
ING = 3
PART = 4
NOUSE = 5
HT = 0
BW = 1
BS = 2
IC = 3
PT = 4
HXGD = 5
YONYOU = 6
YONYOU_ISV = 7


DESCRIPTOR.enum_types_by_name['UserType'] = _USERTYPE
DESCRIPTOR.enum_types_by_name['TransTypeEnum'] = _TRANSTYPEENUM
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['InvoiceTagEnum'] = _INVOICETAGENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034com.hualala.app.invoice.grpcB\rInvoiceCommon'))
# @@protoc_insertion_point(module_scope)
